#!/bin/sh

# Check for Homebrew and install if we don't have it
if test ! $(which brew); then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

# Create folder
mkdir ~/Documents/code
mkdir ~/Documents/code/exceed.ai
mkdir ~/Documents/code/rainbow

# heroku setup
heroku update && heroku plugins:install autocomplete && heroku autocomplet
